# .github/workflows/child_workflow.yml
name: Child Folder Workflow

on:
  repository_dispatch:
    types: [trigger-child-workflow]

jobs:
  build-and-deploy:
    name: Build and Deploy for Child Folder
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node with pnpm
        uses: actions/setup-node@v2
        with:
          node-version: 18
          package-manager: pnpm

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Build project with pnpm
        run: pnpm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
