name: Main Workflow

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./landing-page
